### ISSUE TITLE
Problema com Vtypes

### ISSUE THREAD

**Issue by sk8wagner2006** [wemersonjanuario/modern-locale#4]
Olá @wemersonjanuario  Boa Noite meu parceiro, ótima iniciativa, seria possivel adicionar os vtypes, os validations continuam em inglês. Ex: Meu campo Cnpj possui um inputMask com uma validation presence, quando deixo o campo em branco retorna o erro: Value does not match the required format., conforme mostrado na img em anexo.
![www avalieocorretor com br-app- iphone 6](https://user-images.githubusercontent.com/5194045/32204220-37625b08-bdcf-11e7-8983-9048210a995a.png)

Abraco
Wagner

**Comment by wemersonjanuario** [comment]
Olá Wagner o validator presence já está traduzido, esse erro ai "Value does not match the required format" não é de presença e sim da config badFormatMessage do TextField que está sobrescrita errada acabei de comitar a correção favor testar. Obrigado

badFormatMessage: 'O valor não corresponde ao formato exigido',
