### ISSUE TITLE
下载的压缩包该如何部署？

### ISSUE THREAD

**Issue by lovefox666** [wemersonjanuario/modern-locale#7]
我用EXT创建了通用程序，把下载的压缩包的overrides目录放到modern下，
并修改了app.json文件，sencha app build -testing编译出错。提示如下：

F:\Projects\MyApp>sencha app build -testing
Sencha Cmd v6.5.2.15
[INF] Processing Build Descriptor : classic (testing environment)
[ERR] Cannot satisfy requirements for "modern-locale"!
[ERR]    The following versions cannot be satisfied:
[ERR]       MyApp: modern-locale (No matches!)
[ERR] Cannot resolve package requirements

**Comment by lovelyelfpop** [comment]
English please. Not all of us understand Chinese.

Be aware of the build descriptor, it's `classic` in the output you posted above.
You should use `sencha app build modern` as it's an universal application you are working on.
